name: Update Dynamic README

on:
  push:
    branches:
      - main # or master, depending on your default branch
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate README
        # THIS IS THE CRUCIAL CHANGE: Use the charmbracelet/markscribe action
        uses: charmbracelet/markscribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        with:
          template: "README.md.tpl"
          writeTo: "README.md"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --exit-code || git commit -m "docs: Update dynamic README"
          git push
